# Generated by Django 5.1.2 on 2024-10-31 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_admin_options_alter_articles_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='admin',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='articles',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='bankaccount',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='caisse',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='caissetransaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='chequetransaction',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='clients',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='conge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='contrat',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employeepayment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='employeeproject',
            options={'managed': False},
        ),
    ]
